<a href="https://colab.research.google.com/github/SaiKolapudi/DS_Practice/blob/main/logistic_regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Sai Kolapudi** 

11602684

Develop and evaluate a logistic model to predict the quality (such as high quality and low quality) of red wines according to the several features and calculating test scores. Write your model in Python.

Features that affect wine quality : 'fixed acidity', 'volatile acidity', 'citric acid', 'residual sugar', 'chlorides', 'free sulfur dioxide', 'total sulfur dioxide', 'density', 'pH', 'sulphates', 'alcohol' .

Please split 80% data for training and 20% data for testing.

Calculate the accuracy of the prediction. 

In [26]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler

In [27]:
import io
data=pd.read_csv('/content/winequality-red.csv')

In [28]:
data.head()

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0            7.4              0.70         0.00             1.9      0.076   
1            7.8              0.88         0.00             2.6      0.098   
2            7.8              0.76         0.04             2.3      0.092   
3           11.2              0.28         0.56             1.9      0.075   
4            7.4              0.70         0.00             1.9      0.076   

   free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                 11.0                  34.0   0.9978  3.51       0.56   
1                 25.0                  67.0   0.9968  3.20       0.68   
2                 15.0                  54.0   0.9970  3.26       0.65   
3                 17.0                  60.0   0.9980  3.16       0.58   
4                 11.0                  34.0   0.9978  3.51       0.56   

   alcohol  quality  
0      9.4        5  
1      9.8        5  
2      9.8        5  
3      9.8        6  
4      9.4        5

In [29]:
data.shape

(1599, 12)

In [30]:
## Predictor variable
x=data.iloc[:,0:-1]

In [31]:
## Unique values in the quality
data['quality'].unique()

array([5, 6, 7, 4, 8, 3])

In [32]:
##  we have 6 types of quality, we are deviding it into 3 categories as good,moderate,bad

## 3,4 ===================>bad
## 5,6 ====================>moderate
## 7,8 ======================> good

rating = []
for i in data['quality']:
    if i == 3 or i == 4 or i==5:
        rating.append('1')
    elif i == 6 or i == 7:
        rating.append('2')
    elif i == 7 or i == 8:
        rating.append('3')
data['Reviews'] = rating

In [33]:
## Target variable
y=data['Reviews']

In [34]:
y

0       1
1       1
2       1
3       2
4       1
       ..
1594    1
1595    2
1596    2
1597    1
1598    2
Name: Reviews, Length: 1599, dtype: object

In [37]:
## Splitting the data as 80 % for training and 20 % percent for testing as mentioned 
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test= train_test_split(x,y,test_size=0.2, random_state=42,shuffle=True)

In [38]:
## fitting our data using standardscaler
from sklearn.preprocessing import StandardScaler

In [39]:
nrml=StandardScaler()

x_train=nrml.fit_transform(x_train)
x_test=nrml.fit_transform(x_test)

In [40]:
x_test

array([[-3.33991288e-01,  2.42581186e-01, -9.63136787e-01, ...,
        -4.42561113e-01,  6.34928030e-02, -7.55088351e-01],
       [-2.78643172e-01, -9.49230728e-02, -4.94583756e-01, ...,
         5.19964189e-01, -1.15964614e+00, -8.44713081e-01],
       [ 1.32645219e+00,  8.61338994e-01, -2.34276516e-01, ...,
        -1.85887699e-01,  2.23796204e+00, -4.86214161e-01],
       ...,
       [-1.90259149e-03,  4.67584025e-01, -7.80921719e-02, ...,
        -1.02007629e+00, -8.19885325e-01, -5.75838891e-01],
       [ 2.74837989e-01, -1.38868940e+00,  6.50768099e-01, ...,
        -1.02007629e+00,  2.67349294e-01,  6.78907330e-01],
       [ 4.40882337e-01,  1.39572074e+00, -1.17138258e+00, ...,
        -1.21719346e-01, -7.51933161e-01, -6.65463621e-01]])

In [41]:
## Buiding our logistic Regression Model
from sklearn.linear_model import LogisticRegression

In [42]:
LogReg=LogisticRegression()

In [43]:
LogReg.fit(x_train,y_train)

LogisticRegression()

In [44]:
## Predicting our data
predict=LogReg.predict(x_test)

In [45]:
print(predict)

['1' '1' '2' '1' '2' '1' '1' '1' '2' '2' '2' '1' '2' '1' '1' '2' '1' '1'
 '2' '1' '1' '1' '2' '2' '1' '1' '2' '1' '1' '2' '1' '1' '2' '1' '1' '1'
 '2' '2' '1' '2' '1' '1' '2' '1' '2' '2' '2' '1' '1' '2' '1' '1' '2' '2'
 '1' '1' '2' '1' '2' '1' '2' '2' '1' '1' '2' '1' '2' '1' '2' '1' '2' '1'
 '2' '2' '2' '1' '2' '2' '2' '2' '1' '2' '1' '2' '2' '2' '1' '2' '2' '1'
 '2' '1' '2' '2' '1' '2' '1' '2' '1' '2' '1' '1' '2' '2' '1' '2' '2' '1'
 '2' '1' '2' '1' '2' '1' '2' '2' '2' '1' '1' '2' '2' '1' '2' '1' '1' '1'
 '2' '2' '1' '2' '2' '1' '1' '2' '2' '1' '1' '1' '1' '2' '2' '2' '2' '1'
 '2' '1' '2' '1' '2' '1' '2' '2' '1' '2' '2' '2' '1' '2' '1' '2' '2' '2'
 '2' '1' '1' '2' '1' '1' '1' '1' '1' '1' '2' '1' '1' '2' '2' '1' '1' '1'
 '1' '2' '1' '2' '1' '2' '1' '2' '2' '1' '1' '2' '1' '2' '2' '1' '1' '1'
 '1' '2' '1' '2' '1' '1' '2' '2' '1' '2' '2' '2' '2' '1' '2' '2' '2' '2'
 '1' '1' '2' '1' '1' '2' '2' '2' '1' '1' '1' '2' '1' '1' '1' '1' '2' '2'
 '2' '2' '1' '2' '1' '1' '2' '1' '2' '2' '1' '1' '2

In [46]:
## Caluculating our error
from sklearn import metrics
print("The prediction error of the model1")
print('MAE:', metrics.mean_absolute_error(y_test, predict))
print('MSE:', metrics.mean_squared_error(y_test, predict))
print('RMSE:', np.sqrt(metrics.mean_squared_error(y_test, predict)))

The prediction error of the model1
MAE: 0.275
MSE: 0.275
RMSE: 0.5244044240850758


In [47]:
## Predicting with LR.score accuracy
Accuracy=LogReg.score(x_test, y_test)

In [48]:

Accuracy

0.725

In [55]:

from sklearn.metrics import confusion_matrix
Conf_Matrix = confusion_matrix(y_test, predict)


In [57]:
Conf_Matrix

array([[109,  32,   0],
       [ 51, 123,   0],
       [  0,   5,   0]])

In [60]:
## predicting the accuracy using accuracy_score

from sklearn.metrics import accuracy_score
ac_score = accuracy_score(y_test, predict)

In [61]:
ac_score

0.725